#!/bin/bash
#

### FONCTION
display_message(){
  DIS=`echo $DISPLAY`
  if [ "$DIS" == ":0.0" ]; then
    notify-send "$1" "$2"
  else
    echo "$1" "$2"
  fi
}

display_message "Backup" "Démarrage Backup Projet"
rsync -pavz --progress --stats /home/rkhaiat/projets xxxxx:/home/bacardi55/linagora/ > /home/rkhaiat/script/sortie_backup
cat /home/rkhaiat/script/sortie_backup | mail -s "Backup repertoire projet" xxxx@xxx.org

display_message "Backup" "Fin Backup"
